name: Terraform Artifact Demo file showing working directory and artifcat upload and download information

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
defaults:
  run:
    working-directory: Environment/dev

jobs:

# -------------------------------
# Job-1 : Terraform Plan
# -------------------------------

  terraform-plan:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Print Current Directory
      run: |
        echo "This is Current Directory"
        ls -R
        echo "output kya hai iska smagh nahi a raha hai" 
        find . -name tfplan

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: |
        terraform plan \
        -out=tfplan

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: tfplan

# ----------------------------------
# Job-2 : Terraform Apply
# ----------------------------------

  terraform-apply:

    needs: terraform-plan

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan

    - name: Verify Plan Exists
      run: ls -l

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
